### ISSUE TITLE
where to find the following file?

### ISSUE THREAD

**Issue by liamxg** [andrewvalesano/SARS2_Fall_2020#1]
mugration_output/annotated_tree.nexus

**Comment by LiXingguangBrandonStark** [comment]
could you please share the input files for the scripts, thanks.

**Comment by andrewvalesano** [comment]
Hi Liam,

The virus genomes analyzed in this study are available for download on
GISAID (gisaid.org). Information on which genomes are used in this study
can be found here:
https://github.com/lauringlab/SARS2_Fall_2020/blob/main/data/reference/GISAID_Acknowledgements.xls

Data on case counts are also available on the GitHub page. Data on which
genomes belong to students vs. non-students have not been made publicly
available.

Best,
Andrew

**Comment by liamxg** [comment]
@andrewvalesano what is the column name for student and non-student in the meatadata.tsv?
